name: Update Presence

on:
  schedule:
    - cron: "0 0 * * *" # Workflow jalan jam 00:00 UTC
  workflow_dispatch: # Bisa dijalankan manual juga

jobs:
  update-presence:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Presence
        run: |
          # Dapatkan tanggal hari ini dalam waktu lokal (WIB, UTC+7)
          TODAY=$(date -u '+%Y-%m-%d' -d '+7 hours')
          
          # Update file README.md
          echo "# github-presence" > README.md
          echo "**Present:** $TODAY" >> README.md

      - name: Commit Changes
        run: |
          # Konfigurasi Git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Commit perubahan
          TODAY=$(date -u '+%Y-%m-%d' -d '+7 hours')
          git add README.md
          git commit -m "🌱 present: $TODAY"
          git push
